// GENERATED by bin/precompute-guides.mjs — do not edit by hand.
// Worked-example figures cited in the guide prose, computed from the engine's tax tables for the
// latest registered year so a guide can never show a figure the calculator wouldn't. Regenerate
// with `make precompute-guides` (run automatically by `make bump-year`). Values are pre-formatted
// per language (thousands separators, decimal comma vs point); the prose adds the € prefix.

import type { Lang } from "@/i18n/lang";

/** The tax year these figures were computed for; asserted to equal LATEST_YEAR in the test suite. */
export const GENERATED_FOR_YEAR = 2026;

export const FIGURES: Record<Lang, Record<string, string>> = {
  en: {
    stamp400: "3,200",
    jovemCap: "330,539",
    jovemCapRegion: "413,174",
    jovemUpper: "660,982",
    jovemRate: "8%",
    jovemExcess: "69,461",
    jovemImt: "5,556.88",
    jovemStamp: "555.69",
    jovemTotal: "6,112.57",
    jovemOrdinaryImt: "18,236.65",
    jovemOrdinaryTotal: "21,436.65",
    jovemSaving: "15,300",
    nonResidentImt: "30,000",
    nonResidentTotal: "33,200",
    nonResidentEffRate: "8.3%",
    nonResidentOrdinaryImt: "19,300",
    regionBandLo: "247,934",
    regionBandHi: "413,174",
    regionRate: "7%",
    regionDeduction: "13,072.48",
    regionImt: "14,927.52",
    regionTotal: "18,127.52",
    regionMainlandImt: "18,236.65",
    regionMainlandTotal: "21,436.65",
    regionDiff: "3,300",
  },
  pt: {
    stamp400: "3200",
    jovemCap: "330 539",
    jovemCapRegion: "413 174",
    jovemUpper: "660 982",
    jovemRate: "8%",
    jovemExcess: "69 461",
    jovemImt: "5556,88",
    jovemStamp: "555,69",
    jovemTotal: "6112,57",
    jovemOrdinaryImt: "18 236,65",
    jovemOrdinaryTotal: "21 436,65",
    jovemSaving: "15 300",
    nonResidentImt: "30 000",
    nonResidentTotal: "33 200",
    nonResidentEffRate: "8,3%",
    nonResidentOrdinaryImt: "19 300",
    regionBandLo: "247 934",
    regionBandHi: "413 174",
    regionRate: "7%",
    regionDeduction: "13 072,48",
    regionImt: "14 927,52",
    regionTotal: "18 127,52",
    regionMainlandImt: "18 236,65",
    regionMainlandTotal: "21 436,65",
    regionDiff: "3300",
  },
};
